platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

target 'Straycat' do
    pod 'SwiftSoup', '~> 1.6.3'
    pod 'Alamofire', '~> 4.5'
    pod 'Kanna'
end

target 'StraycatSample' do
end

target 'StraycatTests' do
    use_frameworks!
    pod 'Nimble'
    pod 'Kanna'
    pod 'PySwiftyRegex', '~> 2.0.1'
end
